variable "env" {}
variable "key" {}
variable "region" {}
variable "vpc_cidr_block" {}
variable "public_subnet1" {}
variable "public_subnet2" {}
variable "private_subnet1" {}
variable "az1" {}
variable "az2" {}
variable "az3" {}
variable "az4" {}
variable "az5" {}
variable "az6" {}
variable "ami" {}
variable "min" {}
variable "max" {}
variable "desired_capacity" {}
